/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddApp: typeof import('./src/components/AppCenter/addApp.vue')['default']
    AddBlackListElement: typeof import('./src/components/BlackList/addBlackListElement.vue')['default']
    AppCenter: typeof import('./src/components/AppCenter/index.vue')['default']
    ApplicationCenter: typeof import('./src/components/ApplicationCenter/index.vue')['default']
    BlackList: typeof import('./src/components/BlackList/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    LoginPage: typeof import('./src/components/MainFunction/LoginPage.vue')['default']
    MainPage: typeof import('./src/components/MainFunction/MainPage.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NH2: typeof import('naive-ui')['NH2']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RegisterPage: typeof import('./src/components/MainFunction/RegisterPage.vue')['default']
    ResetPassword: typeof import('./src/components/User/resetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteCenter: typeof import('./src/components/SiteCenter/index.vue')['default']
    UpdateApp: typeof import('./src/components/AppCenter/updateApp.vue')['default']
    UpdateBlackListElement: typeof import('./src/components/BlackList/updateBlackListElement.vue')['default']
    UpdateSite: typeof import('./src/components/SiteCenter/updateSite.vue')['default']
  }
}
