/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMainPage: typeof import('./src/components/AppCenter/AppMainPage.vue')['default']
    AuthorizeAppLogs: typeof import('./src/components/ConsoleCenter/LogsCenter/AuthorizeAppLogs.vue')['default']
    BlackList: typeof import('./src/components/ConsoleCenter/BlackList/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    LoginLogs: typeof import('./src/components/ConsoleCenter/LogsCenter/LoginLogs.vue')['default']
    LoginPage: typeof import('./src/components/MainFunction/LoginPage.vue')['default']
    MainPage: typeof import('./src/components/MainFunction/MainPage.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NH2: typeof import('naive-ui')['NH2']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    RegisterPage: typeof import('./src/components/MainFunction/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteList: typeof import('./src/components/SiteCenter/SiteList.vue')['default']
  }
}
